CVapp1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #busca archivos
from django.conf import settings #Importar contenido del settings

#views applications
from carguecv import views

urlpatterns = [
    #Ruta principal
    path('', views.home, name=""),
    path('admin/', admin.site.urls),
    #Ruta de user
    path('accounts/', include('django.contrib.auth.urls')),
    path('users/', include(('users.urls','users'), namespace='users')),
    #Ruta de las vistas hojas de vida
    path('carguecv/',views.BadgetView.as_view(), name='carguecv'),
    #Ruta de modificacion
    path('<int:pk>', views.BadgetUpdate.as_view(), name='editar'),
    #Ruta de detalles
    path('detail/<int:pk>',views.BadgetDetail.as_view(), name='detail'),
    #Ruta de creación
    path('crear/', views.CreateCV.as_view(), name="crear"),
    #Ruta de uusuarios
    path('users/', include(('users.urls', 'users'), namespace='users')),
    #Ruta de busqueda
    path('buscar/', views.searchCv, name='buscar'),

]
#Indica la rutas de los archivos estaticos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from .views import signup, ActivateUser, templateEmailSent

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>/', ActivateUser, name='activate'),
    path('emailsent/<str:username>/', templateEmailSent, name='emailsent'),
]

templates/base/base.html
{% load static %}
<html>
<head>
  <title>CVapp</title>
  <!--Importacion de librerias-->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/hovereffect.css' %}">
<link rel="stylesheet" href="{% static 'css/font-awesome-4.7.0/css/font-awesome.min.css' %}">
</head>
<body>
<div>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url '' %}">CVAPP</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <!-- Llama la vista de listar hojas de vida -->
            <a class="nav-link" href="{% url 'carguecv' %}"> Vista CV <span class="sr-only">(current)</span></a>
          </li>
        </ul>
        <!-- Llama metodo de busqueda -->
        <form class="form-inline my-2 my-lg-0" action="{% url 'buscar' %}" method="post">
          {% csrf_token %}
          <p><input class="form-control mr-sm-2" type="search" placeholder="Buscar empleado..." name="search" required></p>
          <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Buscar</button>
        </form>
        <!-- Inicio de sesion registro y cierre de sesion -->
        {% if user.is_authenticated %}
              <h6 class="ml-5" style="color:white">Hola {{ user.username }}</h6>
            <a href="{% url 'logout' %}" class="btn btn-info ml-2">Cerrar Sesión</a>
        {% else %}
          <a href="{% url 'users:signup' %}" class="btn btn-light ml-5">Registrarse</a>
          <a href="{% url 'login' %}" class="btn btn-danger ml-2">Iniciar Sesión</a>
        {% endif %}
      </div>
  </nav>

<!-- creacion para incluir la base -->
  {% block content %}
  {% endblock %}
<!-- Invocacion del archivo footer -->

  </div>
  {% include "base/footer.html" %}
</body>
<!--Importacion de librerias-->
<script href="{% static 'bootstrap/css/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/base/footer.html
<!-- Footer -->
<footer class="page-footer font-small bg-dark pt-4 mt-6  fixed-bottom"  style="color:white">

  <div class="container-fluid text-center text-md-left">
    <div class="row">
      <div class="col-md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">Ingreso Hojas de vida Empresarial</h5>
      </div>
      <hr class="clearfix w-100 d-md-none pb-3">
    </div>

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright
    <a style="color: #888888">ANDREA VARGAS - BRIAM BERMUDEZ</a>
  </div>
  <!-- Copyright -->
  </div>
</footer>